# -*- coding: utf-8  -*-
import family

__version__ = '$Id$'


# The Wikimedia family that is known as Wikipedia, the Free Encyclopedia
class Family(family.WikimediaFamily):
    def __init__(self):
        super(Family, self).__init__()
        self.name = 'wikipedia'

        self.languages_by_size = [
            'en', 'nl', 'de', 'fr', 'sv', 'it', 'es', 'ru', 'pl', 'ja', 'vi',
            'pt', 'zh', 'war', 'ceb', 'uk', 'ca', 'no', 'fi', 'fa', 'cs', 'ko',
            'hu', 'ar', 'ro', 'ms', 'sr', 'tr', 'id', 'kk', 'sk', 'eo', 'da',
            'lt', 'eu', 'bg', 'he', 'hr', 'sl', 'uz', 'vo', 'et', 'hi', 'nn',
            'gl', 'simple', 'az', 'la', 'el', 'sh', 'oc', 'th', 'ka', 'mk',
            'new', 'pms', 'be', 'tl', 'ta', 'ht', 'te', 'cy', 'be-x-old', 'lv',
            'tt', 'hy', 'bs', 'br', 'sq', 'jv', 'mg', 'mr', 'lb', 'is', 'ml',
            'my', 'ba', 'yo', 'an', 'lmo', 'fy', 'af', 'pnb', 'bn', 'sw', 'bpy',
            'io', 'ky', 'ur', 'ne', 'zh-yue', 'scn', 'gu', 'nds', 'ga', 'ku',
            'cv', 'ast', 'qu', 'su', 'sco', 'als', 'ia', 'nap', 'bug',
            'bat-smg', 'kn', 'map-bms', 'wa', 'am', 'ckb', 'gd', 'hif',
            'zh-min-nan', 'tg', 'arz', 'mzn', 'yi', 'vec', 'mn', 'sah', 'nah',
            'sa', 'roa-tara', 'os', 'pam', 'si', 'bar', 'hsb', 'se', 'li', 'mi',
            'pa', 'co', 'fo', 'ilo', 'gan', 'bo', 'glk', 'rue', 'bcl', 'frr',
            'fiu-vro', 'nds-nl', 'mrj', 'tk', 'ps', 'vls', 'xmf', 'gv', 'min',
            'diq', 'or', 'kv', 'pag', 'km', 'zea', 'dv', 'mhr', 'nrm', 'csb',
            'vep', 'rm', 'koi', 'udm', 'lad', 'ce', 'lij', 'wuu', 'fur', 'sc',
            'zh-classical', 'stq', 'ug', 'mt', 'ay', 'so', 'pi', 'bh', 'ksh',
            'nov', 'hak', 'kw', 'ang', 'pcd', 'nv', 'gn', 'as', 'ext', 'frp',
            'ace', 'gag', 'eml', 'szl', 'ie', 'ln', 'krc', 'pfl', 'xal', 'haw',
            'pdc', 'rw', 'crh', 'to', 'dsb', 'lez', 'arc', 'kl', 'myv', 'kab',
            'sn', 'bjn', 'pap', 'tpi', 'lbe', 'wo', 'mwl', 'jbo', 'mdf', 'kbd',
            'cbk-zam', 'av', 'srn', 'ty', 'lo', 'ab', 'kg', 'tet', 'ltg', 'na',
            'ig', 'bxr', 'nso', 'za', 'kaa', 'zu', 'chy', 'rmy', 'cu', 'tn',
            'chr', 'roa-rup', 'cdo', 'bi', 'got', 'sm', 'bm', 'iu', 'pih',
            'pnt', 'ss', 'sd', 'ki', 'ee', 'ha', 'om', 'fj', 'ti', 'ts', 'ks',
            'sg', 've', 'rn', 'st', 'cr', 'dz', 'ak', 'tum', 'ik', 'lg', 'ff',
            'ny', 'tw', 'ch', 'xh',
        ]

        self.langs = dict([(lang, '%s.wikipedia.org' % lang)
                           for lang in self.languages_by_size])

        # Override defaults
        self.namespaces[-2]['bar'] = [u'Media', u'Medium']
        self.namespaces[6]['be'] = [u'Файл', u'Выява']
        self.namespaces[7]['be'] = [u'Размовы пра файл', u'Размовы пра выяву']
        self.namespaces[2]['cs'] = [u'Wikipedista', u'Uživatel', u'Wikipedistka']
        self.namespaces[3]['de'] = [u'Benutzer Diskussion', u'BD', u'Benutzerin Diskussion']
        self.namespaces[12]['de'] = [u'Hilfe', u'H']
        self.namespaces[13]['de'] = [u'Hilfe Diskussion', u'HD']
        self.namespaces[2]['hi'] = [u'सदस्य', u'U', u'स']
        self.namespaces[3]['hi'] = [u'सदस्य वार्ता', u'UT', u'सवा']
        self.namespaces[10]['hi'] = [u'साँचा', u'सा', u'T']
        self.namespaces[11]['hi'] = [u'साँचा वार्ता', u'सावा']
        self.namespaces[14]['hi'] = [u'श्रेणी', u'श्र', u'C']
        self.namespaces[15]['hi'] = [u'श्रेणी वार्ता', u'श्रवा', u'CT']
        self.namespaces[1]['ja'] = [u'ノート', u'トーク']
        self.namespaces[3]['ja'] = [u'利用者‐会話', u'利用者・トーク']
        self.namespaces[7]['ja'] = [u'ファイル‐ノート', u'ファイル・トーク', u'Image talk', u'画像‐ノート']
        self.namespaces[9]['ja'] = [u'MediaWiki‐ノート', u'MediaWiki・トーク']
        self.namespaces[10]['ja'] = [u'Template', u'テンプレート']
        self.namespaces[11]['ja'] = [u'Template‐ノート', u'テンプレート・トーク']
        self.namespaces[12]['ja'] = [u'Help', u'ヘルプ']
        self.namespaces[13]['ja'] = [u'Help‐ノート', u'ヘルプ・トーク']
        self.namespaces[14]['ja'] = [u'Category', u'カテゴリ']
        self.namespaces[15]['ja'] = [u'Category‐ノート', u'カテゴリ・トーク']
        self.namespaces[829]['ja'] = [u'モジュール‐ノート', u'モジュール・トーク']
        self.namespaces[12]['nl'] = [u'Help', u'H']
        self.namespaces[2]['ru'] = [u'Участник', u'У', u'Участница']
        self.namespaces[10]['ru'] = [u'Шаблон', u'Ш', u'T']
        self.namespaces[14]['ru'] = [u'Категория', u'К']
        self.namespaces[12]['zh'] = [u'Help', u'H', u'帮助', u'幫助']
        self.namespaces[12]['zh-yue'] = [u'Help', u'H', u'幫手', u'幫助', u'說明', u'帮手', u'帮助', u'说明']

        # Most namespaces are inherited from family.Family.
        # Translation used on all wikis for the different namespaces.
        # (Please sort languages alphabetically)
        # You only need to enter translations that differ from _default.
        self.namespaces[4] = {
            '_default': self.namespaces[4]['_default'],
            'ab': [u'Авикипедиа', u'Wikipedia'],
            'ace': u'Wikipedia',
            'af': u'Wikipedia',
            'ak': u'Wikipedia',
            'als': u'Wikipedia',
            'am': u'ውክፔዲያ',
            'an': u'Wikipedia',
            'ang': u'Wikipedia',
            'ar': [u'ويكيبيديا', u'وب'],
            'arc': [u'ܘܝܩܝܦܕܝܐ', u'Wikipedia'],
            'arz': u'ويكيبيديا',
            'as': [u'ৱিকিপিডিয়া', u'Wikipedia', u'প্ৰকল্প', u'WP'],
            'ast': u'Uiquipedia',
            'av': u'Wikipedia',
            'ay': u'Wikipidiya',
            'az': u'Vikipediya',
            'ba': [u'Википедия', u'Wikipedia'],
            'bar': u'Wikipedia',
            'bat-smg': u'Vikipedėjė',
            'bcl': u'Wikipedia',
            'be': [u'Вікіпедыя', u'ВП'],
            'be-x-old': [u'Вікіпэдыя', u'ВП'],
            'bg': u'Уикипедия',
            'bh': u'विकिपीडिया',
            'bi': u'Wikipedia',
            'bjn': u'Wikipidia',
            'bm': u'Wikipedia',
            'bn': [u'উইকিপিডিয়া', u'Wikipedia', u'WP'],
            'bo': u'Wikipedia',
            'bpy': u'উইকিপিডিয়া',
            'br': u'Wikipedia',
            'bs': u'Wikipedia',
            'bug': u'Wikipedia',
            'bxr': u'Википеэди',
            'ca': u'Viquipèdia',
            'cbk-zam': u'Wikipedia',
            'cdo': u'Wikipedia',
            'ce': [u'Википеди', u'Википедийа'],
            'ceb': u'Wikipedia',
            'ch': u'Wikipedia',
            'chr': u'Wikipedia',
            'chy': u'Wikipedia',
            'ckb': [u'ویکیپیدیا', u'وپ'],
            'co': u'Wikipedia',
            'cr': u'Wikipedia',
            'crh': u'Vikipediya',
            'cs': [u'Wikipedie', u'WP'],
            'csb': u'Wiki',
            'cu': [u'Википєдїꙗ', u'Википє́дїꙗ'],
            'cv': u'Википеди',
            'cy': u'Wicipedia',
            'da': [u'Wikipedia', u'WP'],
            'de': [u'Wikipedia', u'WP'],
            'diq': u'Wikipedia',
            'dsb': u'Wikipedija',
            'dv': u'ވިކިޕީޑި',
            'dz': u'Wikipedia',
            'ee': u'Wikipedia',
            'el': u'Βικιπαίδεια',
            'eml': u'Wikipedia',
            'en': [u'Wikipedia', u'WP'],
            'eo': [u'Vikipedio', u'VP'],
            'es': u'Wikipedia',
            'et': u'Vikipeedia',
            'eu': u'Wikipedia',
            'ext': u'Güiquipeya',
            'fa': [u'ویکی‌پدیا', u'وپ', u'ویکی پدیا', u'ويكي پديا', u'ويکي‌پديا'],
            'ff': u'Wikipedia',
            'fi': [u'Wikipedia', u'WP'],
            'fiu-vro': u'Wikipedia',
            'fj': u'Wikipedia',
            'fo': u'Wikipedia',
            'fr': [u'Wikipédia', u'Wikipedia', u'WP'],
            'frp': u'Vouiquipèdia',
            'frr': u'Wikipedia',
            'fur': u'Vichipedie',
            'fy': u'Wikipedy',
            'ga': u'Vicipéid',
            'gag': u'Vikipediya',
            'gan': u'Wikipedia',
            'gd': [u'Uicipeid', u'Wikipedia'],
            'gl': u'Wikipedia',
            'glk': u'Wikipedia',
            'gn': u'Vikipetã',
            'got': u'Wikipedia',
            'gu': u'વિકિપીડિયા',
            'gv': u'Wikipedia',
            'ha': u'Wikipedia',
            'hak': u'Wikipedia',
            'haw': u'Wikipedia',
            'he': u'ויקיפדיה',
            'hi': [u'विकिपीडिया', u'वि', u'Wikipedia', u'WP'],
            'hif': u'Wikipedia',
            'hr': u'Wikipedija',
            'hsb': u'Wikipedija',
            'ht': [u'Wikipedya', u'Wikipedia'],
            'hu': u'Wikipédia',
            'hy': u'Վիքիպեդիա',
            'ia': u'Wikipedia',
            'id': u'Wikipedia',
            'ie': u'Wikipedia',
            'ig': u'Wikipedia',
            'ik': u'Wikipedia',
            'ilo': [u'Wikipedia', u'WP'],
            'io': [u'Wikipedio', u'Wikipedia'],
            'is': u'Wikipedia',
            'it': [u'Wikipedia', u'WP'],
            'iu': [u'ᐅᐃᑭᐱᑎᐊ', u'Wikipedia'],
            'ja': u'Wikipedia',
            'jbo': u'Wikipedia',
            'jv': u'Wikipedia',
            'ka': u'ვიკიპედია',
            'kaa': u'Wikipedia',
            'kab': u'Wikipedia',
            'kbd': u'Уикипедиэ',
            'kg': u'Wikipedia',
            'ki': u'Wikipedia',
            'kk': u'Уикипедия',
            'kl': u'Wikipedia',
            'km': u'វិគីភីឌា',
            'kn': [u'ವಿಕಿಪೀಡಿಯ', u'Wikipedia'],
            'ko': [u'위키백과', u'백'],
            'koi': u'Википедия',
            'krc': u'Википедия',
            'ks': u'Wikipedia',
            'ksh': u'Wikipedia',
            'ku': u'Wîkîpediya',
            'kv': [u'Википедия', u'Wikipedia'],
            'kw': u'Wikipedia',
            'ky': u'Wikipedia',
            'la': u'Vicipaedia',
            'lad': u'Vikipedya',
            'lb': u'Wikipedia',
            'lbe': u'Википедия',
            'lez': u'Википедия',
            'lg': u'Wikipedia',
            'li': u'Wikipedia',
            'lij': u'Wikipedia',
            'lmo': u'Wikipedia',
            'ln': u'Wikipedia',
            'lo': u'ວິກິພີເດຍ',
            'lt': [u'Vikipedija', u'Wikipedia'],
            'ltg': u'Vikipedeja',
            'lv': [u'Vikipēdija', u'Wikipedia'],
            'map-bms': u'Wikipedia',
            'mdf': u'Википедиесь',
            'mg': u'Wikipedia',
            'mhr': u'Википедий',
            'mi': u'Wikipedia',
            'min': u'Wikipedia',
            'mk': u'Википедија',
            'ml': [u'വിക്കിപീഡിയ', u'വിക്കി', u'Wikipedia', u'WP'],
            'mn': u'Wikipedia',
            'mr': [u'विकिपीडिया', u'Wikipedia', u'विपी'],
            'mrj': u'Википеди',
            'ms': u'Wikipedia',
            'mt': u'Wikipedija',
            'mwl': [u'Biquipédia', u'Wikipedia'],
            'my': u'Wikipedia',
            'myv': u'Википедиясь',
            'mzn': [u'ویکی‌پدیا', u'وپ', u'Wikipedia'],
            'na': u'Wikipedia',
            'nah': [u'Huiquipedia', u'Wikipedia'],
            'nap': u'Wikipedia',
            'nds': [u'Wikipedia', u'WP'],
            'nds-nl': [u'Wikipedie', u'Wikipedia'],
            'ne': [u'विकिपीडिया', u'Wikipedia'],
            'new': u'विकिपिडिया',
            'nl': [u'Wikipedia', u'WP'],
            'nn': [u'Wikipedia', u'WP'],
            'no': [u'Wikipedia', u'WP'],
            'nov': u'Wikipedia',
            'nrm': u'Wikipedia',
            'nso': u'Wikipedia',
            'nv': u'Wikiibíídiiya',
            'ny': u'Wikipedia',
            'oc': u'Wikipèdia',
            'om': u'Wikipedia',
            'or': [u'ଉଇକିପିଡ଼ିଆ', u'Wikipedia', u'WP'],
            'os': u'Википеди',
            'pa': u'ਵਿਕੀਪੀਡੀਆ',
            'pag': u'Wikipedia',
            'pam': u'Wikipedia',
            'pap': u'Wikipedia',
            'pcd': u'Wikipedia',
            'pdc': u'Wikipedia',
            'pfl': u'Wikipedia',
            'pi': u'Wikipedia',
            'pih': u'Wikipedia',
            'pl': [u'Wikipedia', u'WP'],
            'pms': u'Wikipedia',
            'pnb': u'Wikipedia',
            'pnt': u'Βικιπαίδεια',
            'ps': u'ويکيپېډيا',
            'pt': [u'Wikipédia', u'WP', u'Wikipedia'],
            'qu': u'Wikipedia',
            'rm': u'Wikipedia',
            'rmy': u'Vikipidiya',
            'rn': u'Wikipedia',
            'ro': u'Wikipedia',
            'roa-rup': u'Wikipedia',
            'roa-tara': u'Wikipedia',
            'ru': [u'Википедия', u'ВП'],
            'rue': u'Вікіпедія',
            'rw': u'Wikipedia',
            'sa': [u'विकिपीडिया', u'WP', u'Wikipedia'],
            'sah': u'Бикипиэдьийэ',
            'sc': u'Wikipedia',
            'scn': u'Wikipedia',
            'sco': u'Wikipedia',
            'sd': u'Wikipedia',
            'se': [u'Wikipedia', u'WP'],
            'sg': u'Wikipedia',
            'sh': u'Wikipedia',
            'si': [u'විකිපීඩියා', u'Wikipedia'],
            'simple': [u'Wikipedia', u'WP'],
            'sk': u'Wikipédia',
            'sl': u'Wikipedija',
            'sm': u'Wikipedia',
            'sn': u'Wikipedia',
            'so': u'Wikipedia',
            'sq': u'Wikipedia',
            'sr': [u'Википедија', u'Vikipedija'],
            'srn': u'Wikipedia',
            'ss': u'Wikipedia',
            'st': u'Wikipedia',
            'stq': u'Wikipedia',
            'su': u'Wikipedia',
            'sv': [u'Wikipedia', u'WP'],
            'sw': u'Wikipedia',
            'szl': u'Wikipedyjo',
            'ta': [u'விக்கிப்பீடியா', u'Wikipedia', u'விக்கிபீடியா'],
            'te': [u'వికీపీడియా', u'Wikipedia'],
            'tet': u'Wikipedia',
            'tg': u'Википедиа',
            'th': u'วิกิพีเดีย',
            'ti': u'Wikipedia',
            'tk': u'Wikipediýa',
            'tl': u'Wikipedia',
            'tn': u'Wikipedia',
            'to': u'Wikipedia',
            'tpi': u'Wikipedia',
            'tr': u'Vikipedi',
            'ts': u'Wikipedia',
            'tt': [u'Википедия', u'WP', u'ВП', u'Wikipedia'],
            'tum': u'Wikipedia',
            'tw': u'Wikipedia',
            'ty': u'Wikipedia',
            'udm': u'Википедия',
            'ug': u'Wikipedia',
            'uk': [u'Вікіпедія', u'ВП'],
            'ur': u'ویکیپیڈیا',
            'uz': [u'Vikipediya', u'VP'],
            've': u'Wikipedia',
            'vec': [u'Wikipedia', u'WP'],
            'vep': u'Vikipedii',
            'vi': u'Wikipedia',
            'vls': u'Wikipedia',
            'vo': [u'Vükiped', u'Wikipedia'],
            'wa': u'Wikipedia',
            'war': u'Wikipedia',
            'wo': u'Wikipedia',
            'wuu': u'Wikipedia',
            'xal': u'Wikipedia',
            'xh': u'Wikipedia',
            'xmf': u'ვიკიპედია',
            'yi': [u'װיקיפּעדיע', u'וויקיפעדיע'],
            'yo': u'Wikipedia',
            'za': u'Wikipedia',
            'zea': u'Wikipedia',
            'zh': [u'Wikipedia', u'维基百科', u'維基百科', u'WP'],
            'zh-classical': [u'維基大典', u'Wikipedia', u'Wikipedia talk'],
            'zh-min-nan': u'Wikipedia',
            'zh-yue': [u'Wikipedia', u'WP'],
            'zu': u'Wikipedia',
        }

        self.namespaces[5] = {
            '_default': self.namespaces[5]['_default'],
            'ab': [u'Авикипедиа ахцәажәара', u'Обсуждение Авикипедиа'],
            'ace': [u'Marit Wikipedia', u'Pembicaraan Wikipedia'],
            'af': u'Wikipediabespreking',
            'ak': u'Wikipedia nkɔmbɔ',
            'als': u'Wikipedia Diskussion',
            'am': u'ውክፔዲያ ውይይት',
            'an': u'Descusión Wikipedia',
            'ang': u'Wikipedia talk',
            'ar': [u'نقاش ويكيبيديا', u'نو'],
            'arc': u'ܡܡܠܠܐ ܕܘܝܩܝܦܕܝܐ',
            'arz': u'نقاش ويكيبيديا',
            'as': [u'ৱিকিপিডিয়া বাৰ্তা', u'Wikipedia talk', u'প্ৰকল্প আলোচনা', u'Wikipedia বার্তা', u'ৱিকিপিডিয়া वार्ता', u'ৱিকিপিডিয়া বার্তা'],
            'ast': [u'Uiquipedia alderique', u'Uiquipedia discusión'],
            'av': u'Обсуждение Wikipedia',
            'ay': u'Wikipidiyan Aruskipäwi',
            'az': u'Vikipediya müzakirəsi',
            'ba': [u'Википедия буйынса фекерләшеү', u'Wikipedia буйынса фекерләшеү', u'Википедия б-са фекер алышыу'],
            'bar': [u'Wikipedia Dischkrian', u'Wikipedia Diskussion'],
            'bat-smg': [u'Vikipedėjės aptarėms', u'Vikipedėjė aptarimas'],
            'bcl': u'Olay sa Wikipedia',
            'be': [u'Размовы пра Вікіпедыя', u'Вікіпедыя размовы'],
            'be-x-old': [u'Абмеркаваньне Вікіпэдыі', u'Абмеркаваньне Вікіпэдыя'],
            'bg': u'Уикипедия беседа',
            'bh': u'विकिपीडिया वार्ता',
            'bi': u'Wikipedia talk',
            'bjn': [u'Pamandiran Wikipidia', u'Wikipidia pamandiran', u'Pembicaraan Wikipidia'],
            'bm': u'Discussion Wikipedia',
            'bn': [u'উইকিপিডিয়া আলোচনা', u'WT', u'উইকিপিডিয়া আলাপ'],
            'bo': u'Wikipedia talk',
            'bpy': [u'উইকিপিডিয়া য়্যারী', u'উইকিপিডিয়া আলাপ'],
            'br': [u'Kaozeadenn Wikipedia', u'Discussion Wikipedia'],
            'bs': u'Razgovor s Wikipediom',
            'bug': u'Pembicaraan Wikipedia',
            'bxr': [u'Википеэди тухай хэлэлсэхэ', u'Обсуждение Википеэди'],
            'ca': u'Viquipèdia Discussió',
            'cbk-zam': u'Wikipedia discusión',
            'cdo': u'Wikipedia talk',
            'ce': [u'Википедин дийцаре', u'Википедийа дийцаре', u'Википеди Дийца', u'Дийцаре Википеди'],
            'ceb': [u'Hisgot sa Wikipedia', u'Hisgot saWikipedia'],
            'ch': u'Kombetsasion nu Wikipedia',
            'chr': u'Wikipedia talk',
            'chy': u'Wikipedia talk',
            'ckb': u'لێدوانی ویکیپیدیا',
            'co': u'Wikipedia talk',
            'cr': u'Wikipedia talk',
            'crh': [u'Vikipediya muzakeresi', u'Vikipediya музакереси'],
            'cs': [u'Diskuse k Wikipedii', u'Wikipedie diskuse'],
            'csb': u'Diskùsëjô Wiki',
            'cu': [u'Википєдїѩ бєсѣ́да', u'Википє́дїѩ бєсѣ́да', u'Википєдїꙗ бесѣда'],
            'cv': u'Википеди сӳтсе явмалли',
            'cy': u'Sgwrs Wicipedia',
            'da': u'Wikipedia-diskussion',
            'de': [u'Wikipedia Diskussion', u'WD'],
            'diq': [u'Wikipedia mesac', u'Wikipedia werênayış'],
            'dsb': u'Wikipedija diskusija',
            'dv': [u'ވިކިޕީޑިއާ ޚިޔާ', u'Wikipedia talk'],
            'dz': u'Wikipedia talk',
            'ee': u'Wikipedia talk',
            'el': [u'Συζήτηση Βικιπαίδεια', u'Βικιπαίδεια συζήτηση'],
            'eml': u'Discussioni Wikipedia',
            'en': [u'Wikipedia talk', u'WT'],
            'eo': [u'Vikipedia diskuto', u'Vikipedio diskuto'],
            'es': u'Wikipedia discusión',
            'et': u'Vikipeedia arutelu',
            'eu': u'Wikipedia eztabaida',
            'ext': u'Güiquipeya talk',
            'fa': [u'بحث ویکی‌پدیا', u'بحث ویکی پدیا', u'بحث ويکي پديا', u'بحث ويکي‌پديا'],
            'ff': u'Discussion Wikipedia',
            'fi': u'Keskustelu Wikipediasta',
            'fiu-vro': [u'Wikipedia arotus', u'Wikipedia arutelu'],
            'fj': u'Wikipedia talk',
            'fo': [u'Wikipedia-kjak', u'Wikipedia kjak'],
            'fr': [u'Discussion Wikipédia', u'Discussion Wikipedia'],
            'frp': u'Discussion Vouiquipèdia',
            'frr': u'Wikipedia Diskussion',
            'fur': u'Discussion Vichipedie',
            'fy': u'Wikipedy oerlis',
            'ga': u'Plé Vicipéide',
            'gag': [u'Vikipediyanın laflanması', u'Vikipediya tartışma'],
            'gan': [u'Wikipedia・談詑', u'Wikipedia 談詑'],
            'gd': [u'An deasbaireachd aig Uicipeid', u'Wikipedia talk'],
            'gl': u'Conversa Wikipedia',
            'glk': u'بحث Wikipedia',
            'gn': u'Vikipetã myangekõi',
            'got': u'𐌸𐌹𐍃 Wikipedia 𐌲𐌰𐍅𐌰𐌿𐍂𐌳𐌾𐌰',
            'gu': u'વિકિપીડિયા ચર્ચા',
            'gv': u'Resooney Wikipedia',
            'ha': u'Wikipedia talk',
            'hak': u'Wikipedia talk',
            'haw': u'Kūkākūkā o Wikipikia',
            'he': u'שיחת ויקיפדיה',
            'hi': [u'विकिपीडिया वार्ता', u'विवा', u'WPT'],
            'hif': u'Wikipedia baat',
            'hr': u'Razgovor Wikipedija',
            'hsb': u'Wikipedija diskusija',
            'ht': [u'Diskisyon Wikipedya', u'Wikipedia talk'],
            'hu': [u'Wikipédia-vita', u'Wikipédia vita'],
            'hy': u'Վիքիպեդիայի քննարկում',
            'ia': u'Discussion Wikipedia',
            'id': u'Pembicaraan Wikipedia',
            'ie': u'Wikipedia Discussion',
            'ig': u'Okwu Wikipedia',
            'ik': u'Wikipedia talk',
            'ilo': [u'Wikipedia tungtungan', u'WT'],
            'io': [u'Wikipedio Debato', u'Wikipedia talk'],
            'is': u'Wikipediaspjall',
            'it': u'Discussioni Wikipedia',
            'iu': [u'ᐅᐃᑭᐱᑎᐊ talk', u'Wikipedia talk'],
            'ja': [u'Wikipedia‐ノート', u'Wikipedia・トーク'],
            'jbo': u'Wikipedia talk',
            'jv': u'Dhiskusi Wikipedia',
            'ka': u'ვიკიპედია განხილვა',
            'kaa': [u'Wikipedia sa\'wbeti', u'Wikipedia талқылауы', u'Wikipedia تالقىلاۋى'],
            'kab': u'Amyannan n Wikipedia',
            'kbd': [u'Уикипедиэм и тепсэлъыхьыгъуэ', u'Обсуждение Уикипедиэ'],
            'kg': u'Disolo Wikipedia',
            'ki': u'Wikipedia talk',
            'kk': [u'Уикипедия талқылауы', u'Уикипедия talqılawı', u'Уикипедия تالقىلاۋى'],
            'kl': [u'Wikipedia-p oqalliffia', u'Wikipedia-diskussion', u'Wikipediaip oqalliffia'],
            'km': [u'ការពិភាក្សាអំពីវិគីភីឌា', u'វិគីភីឌា ពិភាក្ស'],
            'kn': [u'ವಿಕಿಪೀಡಿಯ ಚರ್ಚೆ', u'Wikipedia talk'],
            'ko': [u'위키백과토론', u'백토'],
            'koi': u'Баитам Википедия йылiсь',
            'krc': u'Википедия сюзюу',
            'ks': u'Wikipedia بَحَژ',
            'ksh': u'Wikipedia Klaaf',
            'ku': [u'Gotûbêja Wîkîpediyayê', u'Wîkîpediya nîqaş'],
            'kv': [u'Википедия донъялӧм', u'Обсуждение Wikipedia', u'Обсуждение Википедии'],
            'kw': [u'Keskows Wikipedia', u'Cows Wikipedia', u'Kescows Wikipedia'],
            'ky': u'Wikipedia баарлашуу',
            'la': [u'Disputatio Vicipaediae', u'Disputatio Wikipedia'],
            'lad': [u'Diskusyón de Vikipedya', u'Vikipedya Discusión', u'Diskussión de Vikipedya'],
            'lb': u'Wikipedia Diskussioun',
            'lbe': u'Википедиялиясса ихтилат',
            'lez': [u'Википедия веревирд авун', u'Обсуждение Википедии'],
            'lg': u'Wikipedia talk',
            'li': u'Euverlèk Wikipedia',
            'lij': [u'Discûscioîn Wikipedia', u'Discussioni Wikipedia'],
            'lmo': [u'Wikipedia Ciciarada', u'Discussioni Wikipedia'],
            'ln': u'Discussion Wikipedia',
            'lo': u'ສົນທະນາກ່ຽວກັບວິກິພີເດຍ',
            'lt': [u'Vikipedijos aptarimas', u'Wikipedia aptarimas'],
            'ltg': u'Vikipedejis sprīža',
            'lv': u'Vikipēdijas diskusija',
            'map-bms': u'Dhiskusi Wikipedia',
            'mdf': [u'Википедиесь корхнема', u'Обсуждение Википедиесь'],
            'mg': [u'Dinika amin\'ny Wikipedia', u'Discussion Wikipedia'],
            'mhr': [u'Википедийын каҥашымашыже', u'Обсуждение Википедий', u'Википедийын каҥашымаш'],
            'mi': u'Wikipedia talk',
            'min': [u'Rundiang Wikipedia', u'Pembicaraan Wikipedia'],
            'mk': u'Разговор за Википедија',
            'ml': [u'വിക്കിപീഡിയ സംവാദം', u'വിക്കിസം'],
            'mn': u'Wikipedia-н хэлэлцүүлэг',
            'mr': u'विकिपीडिया चर्चा',
            'mrj': u'Википедим кӓнгӓшӹмӓш',
            'ms': [u'Perbincangan Wikipedia', u'Perbualan Wikipedia'],
            'mt': [u'Diskussjoni Wikipedija', u'Wikipedija diskuti', u'Wikipedija diskussjoni'],
            'mwl': [u'Biquipédia cumbersa', u'Wikipedia cumbersa', u'Biquipédia Discussão'],
            'my': u'Wikipedia talk',
            'myv': u'Википедиясь кортамось',
            'mzn': [u'ویکی پدیا گپ', u'Wikipedia گپ', u'بحث ویکی‌پدیا'],
            'na': u'Wikipedia talk',
            'nah': [u'Huiquipedia tēixnāmiquiliztli', u'Wikipedia tēixnāmiquiliztli', u'Wikipedia Discusión'],
            'nap': [u'Wikipedia chiàcchiera', u'Discussioni Wikipedia'],
            'nds': [u'Wikipedia Diskuschoon', u'Wikipedia Diskussion'],
            'nds-nl': u'Overleg Wikipedie',
            'ne': u'विकिपीडिया वार्ता',
            'new': u'विकिपिडिया खँलाबँला',
            'nl': u'Overleg Wikipedia',
            'nn': u'Wikipedia-diskusjon',
            'no': u'Wikipedia-diskusjon',
            'nov': u'Wikipedia talk',
            'nrm': u'Wikipedia talk',
            'nso': u'Dipolelo tša Wikipedia',
            'nv': u'Wikiibíídiiya baa yáshtiʼ',
            'ny': u'Wikipedia talk',
            'oc': u'Discussion Wikipèdia',
            'om': u'Wikipedia talk',
            'or': [u'ଉଇକିପିଡ଼ିଆ ଆଲୋଚନା', u'Wikipedia talk', u'WT'],
            'os': [u'Википедийы тæрхон', u'Дискусси Википеди'],
            'pa': [u'ਵਿਕੀਪੀਡੀਆ ਗੱਲ-ਬਾਤ', u'ਵਿਕੀਪੀਡੀਆ ਚਰਚਾ'],
            'pag': u'Wikipedia talk',
            'pam': u'Wikipedia talk',
            'pap': u'Wikipedia talk',
            'pcd': u'Discussion Wikipedia',
            'pdc': [u'Wikipedia Dischbedutt', u'Wikipedia Diskussion'],
            'pfl': [u'Wikipedia Dischbediere', u'Wikipedia Diskussion'],
            'pi': u'Wikipedia सम्भासित',
            'pih': u'Wikipedia talk',
            'pl': u'Dyskusja Wikipedii',
            'pms': u'Discussion ant sla Wikipedia',
            'pnb': u'Wikipedia talk',
            'pnt': u'Βικιπαίδεια καλάτσεμαν',
            'ps': u'د ويکيپېډيا خبرې اترې',
            'pt': [u'Wikipédia Discussão', u'Wikipedia Discussão'],
            'qu': u'Wikipedia rimanakuy',
            'rm': u'Wikipedia discussiun',
            'rmy': [u'Vikipidiyake vakyarimata', u'Discuţie Vikipidiya'],
            'rn': u'Wikipedia talk',
            'ro': [u'Discuție Wikipedia', u'Discuţie Wikipedia'],
            'roa-rup': u'Wikipedia talk',
            'roa-tara': u'Wikipedia talk',
            'ru': u'Обсуждение Википедии',
            'rue': u'Діскузія ку Вікіпедії',
            'rw': u'Wikipedia talk',
            'sa': [u'विकिपीडियासम्भाषणम्', u'WT', u'Wikipedia talk', u'विकिपीडियासंभाषणं'],
            'sah': u'Бикипиэдьийэ ырытыыта',
            'sc': [u'Cuntierra Wikipedia', u'Wikipedia discussioni'],
            'scn': u'Discussioni Wikipedia',
            'sco': u'Wikipedia talk',
            'sd': u'Wikipedia بحث',
            'se': u'Wikipedia-ságastallan',
            'sg': u'Discussion Wikipedia',
            'sh': u'Razgovor o Wikipedia',
            'si': [u'විකිපීඩියා සාකච්ඡාව', u'Wikipedia talk'],
            'simple': u'Wikipedia talk',
            'sk': [u'Diskusia k Wikipédii', u'Komentár k Wikipédii'],
            'sl': u'Pogovor o Wikipediji',
            'sm': u'Wikipedia talk',
            'sn': u'Wikipedia talk',
            'so': u'Wikipedia talk',
            'sq': u'Wikipedia diskutim',
            'sr': [u'Разговор о Википедији', u'Razgovor o Википедија'],
            'srn': [u'Taki fu Wikipedia', u'Overleg Wikipedia'],
            'ss': u'Wikipedia talk',
            'st': u'Wikipedia talk',
            'stq': u'Wikipedia Diskussion',
            'su': u'Obrolan Wikipedia',
            'sv': u'Wikipediadiskussion',
            'sw': [u'Majadiliano ya Wikipedia', u'Wikipedia majadiliano'],
            'szl': [u'Dyskusyjo Wikipedyjo', u'Dyskusja Wikipedyjo'],
            'ta': [u'விக்கிப்பீடியா பேச்சு', u'Wikipedia talk', u'விக்கிபீடியா பேச்சு'],
            'te': [u'వికీపీడియా చర్చ', u'Wikipedia talk'],
            'tet': u'Diskusaun Wikipedia',
            'tg': u'Баҳси Википедиа',
            'th': u'คุยเรื่องวิกิพีเดีย',
            'ti': u'Wikipedia talk',
            'tk': u'Wikipediýa çekişme',
            'tl': u'Usapang Wikipedia',
            'tn': u'Wikipedia talk',
            'to': u'Wikipedia talk',
            'tpi': u'Wikipedia toktok',
            'tr': u'Vikipedi tartışma',
            'ts': u'Wikipedia talk',
            'tt': [u'Википедия бәхәсе', u'Wikipedia talk', u'Обсуждение Википедии', u'Википедия bäxäse'],
            'tum': u'Wikipedia talk',
            'tw': u'Wikipedia talk',
            'ty': u'Discussion Wikipedia',
            'udm': [u'Википедия сярысь вераськон', u'Wikipedia сярысь вераськон'],
            'ug': [u'Wikipediaمۇنازىرىسى', u'مۇنازىرىسىWikipedia'],
            'uk': u'Обговорення Вікіпедії',
            'ur': u'تبادلۂ خیال ویکیپیڈیا',
            'uz': [u'Vikipediya munozarasi', u'VM'],
            've': u'Wikipedia talk',
            'vec': u'Discussion Wikipedia',
            'vep': [u'Paginad Vikipedii', u'Vikipedii arutelu'],
            'vi': u'Thảo luận Wikipedia',
            'vls': u'Discuusje Wikipedia',
            'vo': [u'Bespik dö Vükiped', u'Wikipedia talk'],
            'wa': u'Wikipedia copene',
            'war': u'Hiruhimangraw hiton Wikipedia',
            'wo': [u'Wikipedia waxtaan', u'Discussion Wikipedia'],
            'wuu': u'Wikipedia讨论',
            'xal': [u'Wikipedia туск меткән', u'Wikipedia тускар ухалвр'],
            'xh': u'Wikipedia talk',
            'xmf': u'ვიკიპედია სხუნუა',
            'yi': [u'װיקיפּעדיע רעדן', u'וויקיפעדיע רעדן'],
            'yo': u'Ọ̀rọ̀ Wikipedia',
            'za': u'Wikipedia讨论',
            'zea': u'Overleg Wikipedia',
            'zh': [u'Wikipedia talk', u'维基百科讨论', u'维基百科对话', u'維基百科討論', u'維基百科對話', u'WT'],
            'zh-classical': u'維基大典 talk',
            'zh-min-nan': u'Wikipedia talk',
            'zh-yue': [u'Wikipedia talk', u'WT', u'Wikipedia 傾偈'],
            'zu': u'Wikipedia talk',
        }

        self.namespaces[90] = {
            'hu': u'Téma',
        }

        self.namespaces[91] = {
            'hu': u'Témavita',
        }

        self.namespaces[92] = {
            'hu': u'Összefoglaló',
        }

        self.namespaces[93] = {
            'hu': u'Összefoglaló-vita',
        }

        self.namespaces[100] = {
            'af': u'Portaal',
            'als': u'Portal',
            'am': u'በር',
            'an': u'Portal',
            'ar': u'بوابة',
            'arz': u'بوابة',
            'as': u'ৱিকিচ\'ৰা',
            'az': u'Portal',
            'ba': u'Портал',
            'bar': u'Portal',
            'be': u'Партал',
            'be-x-old': u'Партал',
            'bg': u'Портал',
            'bn': u'প্রবেশদ্বার',
            'bpy': u'হমিলদুৱার',
            'bs': u'Portal',
            'ca': u'Portal',
            'ce': u'Ков',
            'ckb': u'دەروازە',
            'cs': u'Portál',
            'cy': u'Porth',
            'da': u'Portal',
            'de': u'Portal',
            'dv': u'ނެރު',
            'el': u'Πύλη',
            'en': u'Portal',
            'eo': u'Portalo',
            'es': u'Portal',
            'et': u'Portaal',
            'eu': u'Atari',
            'fa': u'درگاه',
            'fi': u'Teemasivu',
            'fr': u'Portail',
            'gl': u'Portal',
            'he': u'פורטל',
            'hi': u'प्रवेशद्वार',
            'hr': u'Portal',
            'hu': u'Portál',
            'hy': u'Պորտալ',
            'ia': u'Portal',
            'id': u'Portal',
            'is': u'Gátt',
            'it': u'Portale',
            'ja': u'Portal',
            'ka': u'პორტალი',
            'kk': u'Портал',
            'ko': u'들머리',
            'ku': u'Portal',
            'kw': u'Porth',
            'la': u'Porta',
            'li': u'Portaol',
            'lmo': u'Portal',
            'lt': u'Vikisritis',
            'lv': u'Portāls',
            'min': u'Portal',
            'mk': u'Портал',
            'ml': u'കവാടം',
            'mr': u'दालन',
            'ms': u'Portal',
            'mt': u'Portal',
            'mzn': u'پورتال',
            'nds': u'Portal',
            'new': u'दबू',
            'nl': u'Portaal',
            'nn': u'Tema',
            'no': u'Portal',
            'oc': u'Portal',
            'pfl': u'Portal',
            'pl': u'Portal',
            'pt': u'Portal',
            'ro': u'Portal',
            'roa-tara': u'Portale',
            'ru': u'Портал',
            'scn': u'Purtali',
            'se': u'Portála',
            'sh': u'Portal',
            'si': u'ද්වාරය',
            'sk': u'Portál',
            'sl': u'Portal',
            'sq': u'Portal',
            'sr': u'Портал',
            'su': u'Portal',
            'sv': u'Portal',
            'sw': u'Lango',
            'ta': u'வலைவாசல்',
            'te': u'వేదిక',
            'tg': u'Портал',
            'th': u'สถานีย่อย',
            'tl': u'Portada',
            'tr': u'Portal',
            'tt': u'Портал',
            'uk': u'Портал',
            'ur': u'باب',
            'uz': u'Portal',
            'vec': u'Portałe',
            'vi': u'Chủ đề',
            'wuu': u'Transwiki',
            'yi': u'פארטאל',
            'yo': u'Èbúté',
            'zh': u'Portal',
            'zh-classical': u'門',
            'zh-min-nan': u'Portal',
            'zh-yue': u'Portal',
        }

        self.namespaces[101] = {
            'af': u'Portaalbespreking',
            'als': u'Portal Diskussion',
            'am': u'በር ውይይት',
            'an': u'Descusión Portal',
            'ar': u'نقاش البوابة',
            'arz': [u'مناقشة بوابة', u'Portal talk'],
            'as': u'ৱিকিচ\'ৰা আলোচনা',
            'az': u'Portal müzakirəsi',
            'ba': u'Портал буйынса фекерләшеү',
            'bar': u'Portal Dischkrian',
            'be': [u'Размовы пра партал', u'Portal talk'],
            'be-x-old': u'Абмеркаваньне парталу',
            'bg': u'Портал беседа',
            'bn': [u'প্রবেশদ্বার আলোচনা', u'Portal talk', u'കവാടത്തിന്റെ സംവാദം'],
            'bpy': [u'হমিলদুৱার য়্যারী', u'Portal talk'],
            'bs': u'Razgovor o portalu',
            'ca': u'Portal Discussió',
            'ce': u'Ков дийцаре',
            'ckb': u'لێدوانی دەروازە',
            'cs': [u'Diskuse k portálu', u'Portal talk', u'Portál diskuse'],
            'cy': u'Sgwrs Porth',
            'da': [u'Portaldiskussion', u'Portal diskussion'],
            'de': [u'Portal Diskussion', u'PD'],
            'dv': [u'ނެރު ޚ ޔާލު', u'Portal talk'],
            'el': u'Συζήτηση πύλης',
            'en': u'Portal talk',
            'eo': u'Portala diskuto',
            'es': u'Portal Discusión',
            'et': [u'Portaali arutelu', u'Portal talk'],
            'eu': u'Atari eztabaida',
            'fa': u'بحث درگاه',
            'fi': u'Keskustelu teemasivusta',
            'fr': u'Discussion Portail',
            'gl': u'Conversa portal',
            'he': u'שיחת פורטל',
            'hi': [u'प्रवेशद्वार वार्ता', u'प्रवा'],
            'hr': u'Razgovor o portalu',
            'hu': [u'Portálvita', u'Portál vita'],
            'hy': u'Պորտալի քննարկում',
            'ia': u'Discussion Portal',
            'id': u'Pembicaraan Portal',
            'is': u'Gáttaspjall',
            'it': u'Discussioni portale',
            'ja': [u'Portal‐ノート', u'ポータル‐ノート', u'Portal・トーク'],
            'ka': u'პორტალი განხილვა',
            'kk': u'Портал талқылауы',
            'ko': [u'들머리토론', u'Portal talk', u'들토'],
            'ku': [u'Gotûbêja portalê', u'Portal nîqaş'],
            'kw': u'Keskows Porth',
            'la': u'Disputatio Portae',
            'li': u'Euverlèk portaol',
            'lmo': u'Descüssiú Portal',
            'lt': u'Vikisrities aptarimas',
            'lv': u'Portāla diskusija',
            'min': u'Diskusi Portal',
            'mk': u'Разговор за Портал',
            'ml': [u'കവാടത്തിന്റെ സംവാദം', u'Portal talk'],
            'mr': u'दालन चर्चा',
            'ms': [u'Perbualan Portal', u'Portal talk'],
            'mt': u'Diskussjoni portal',
            'mzn': [u'پورتال گپ', u'Portal talk'],
            'nds': u'Portal Diskuschoon',
            'new': u'दबू खँलाबँला',
            'nl': u'Overleg portaal',
            'nn': u'Temadiskusjon',
            'no': u'Portaldiskusjon',
            'oc': u'Discussion Portal',
            'pfl': u'Portal Diskussion',
            'pl': u'Dyskusja portalu',
            'pt': [u'Portal Discussão', u'Discussão Portal'],
            'ro': [u'Discuție Portal', u'Discuţie Portal'],
            'roa-tara': u'\'Ngazzaminde d\'u Portale',
            'ru': u'Обсуждение портала',
            'scn': u'Discussioni purtali',
            'se': u'Portálaságastallan',
            'sh': u'Razgovor o portalu',
            'si': [u'ද්වාරය සාකච්ඡාව', u'Portal talk'],
            'sk': u'Diskusia k portálu',
            'sl': u'Pogovor o portalu',
            'sq': u'Portal diskutim',
            'sr': u'Разговор о порталу',
            'su': u'Obrolan portal',
            'sv': u'Portaldiskussion',
            'sw': [u'Majadiliano ya lango', u'Portal talk'],
            'ta': u'வலைவாசல் பேச்சு',
            'te': u'వేదిక చర్చ',
            'tg': u'Баҳси портал',
            'th': u'คุยเรื่องสถานีย่อย',
            'tl': u'Usapang Portada',
            'tr': u'Portal tartışma',
            'tt': u'Портал бәхәсе',
            'uk': u'Обговорення порталу',
            'ur': u'تبادلۂ خیال باب',
            'uz': u'Portal munozarasi',
            'vec': u'Discussion portałe',
            'vi': u'Thảo luận Chủ đề',
            'wuu': u'Transwiki talk',
            'yi': u'פארטאל רעדן',
            'yo': [u'Ọ̀rọ̀ èbúté', u'Portal talk'],
            'zh': u'Portal talk',
            'zh-classical': u'議',
            'zh-min-nam': u'Portal talk',
            'zh-min-nan': u'Portal talk',
            'zh-yue': u'Portal talk',
        }

        self.namespaces[102] = {
            'als': u'Buech',
            'ba': u'Проект',
            'bar': u'Buach',
            'ca': u'Viquiprojecte',
            'cs': u'Rejstřík',
            'da': u'Artikeldata',
            'eo': u'Projekto',
            'es': u'Wikiproyecto',
            'eu': u'Wikiproiektu',
            'fa': u'کتاب',
            'fi': u'Metasivu',
            'fr': u'Projet',
            'frr': u'Seite',
            'gl': u'Libro',
            'hr': u'Dodatak',
            'ia': u'Appendice',
            'it': u'Progetto',
            'ja': u'プロジェクト',
            'kk': u'Жоба',
            'ko': u'위키프로젝트',
            'lmo': u'Purtaal',
            'lt': u'Vikiprojektas',
            'lv': u'Vikiprojekts',
            'oc': u'Projècte',
            'pl': u'Wikiprojekt',
            'pt': u'Anexo',
            'ro': u'Proiect',
            'ru': u'Инкубатор',
            'scn': u'Pruggettu',
            'uz': u'Loyiha',
            'vec': u'Projeto',
        }

        self.namespaces[103] = {
            'als': u'Buech Diskussion',
            'ba': u'Проект буйынса фекерләшеү',
            'bar': u'Buach Dischkrian',
            'ca': u'Viquiprojecte Discussió',
            'cs': u'Diskuse k rejstříku',
            'da': u'Artikeldatadiskussion',
            'eo': u'Projekta diskuto',
            'es': u'Wikiproyecto Discusión',
            'eu': u'Wikiproiektu eztabaida',
            'fa': u'بحث کتاب',
            'fi': u'Keskustelu metasivusta',
            'fr': u'Discussion Projet',
            'frr': u'Seite Diskussion',
            'gl': u'Conversa libro',
            'hr': u'Razgovor o dodatku',
            'ia': u'Discussion Appendice',
            'it': u'Discussioni progetto',
            'ja': u'プロジェクト‐ノート',
            'kk': u'Жоба талқылауы',
            'ko': u'위키프로젝트토론',
            'lmo': u'Descüssiun Purtaal',
            'lt': u'Vikiprojekto aptarimas',
            'lv': u'Vikiprojekta diskusija',
            'oc': u'Discussion Projècte',
            'pl': u'Dyskusja wikiprojektu',
            'pt': u'Anexo Discussão',
            'ro': u'Discuție Proiect',
            'ru': u'Обсуждение Инкубатора',
            'scn': u'Discussioni pruggettu',
            'uz': u'Loyiha munozarasi',
            'vec': u'Discussion projeto',
        }

        self.namespaces[104] = {
            'als': u'Wort',
            'ar': u'ملحق',
            'bar': u'Woat',
            'es': u'Anexo',
            'fi': u'Kirja',
            'fr': u'Référence',
            'frr': u'Index',
            'lt': u'Sąrašas',
            'pt': u'Livro',
            'ru': u'Проект',
        }

        self.namespaces[105] = {
            'als': u'Wort Diskussion',
            'ar': u'نقاش الملحق',
            'bar': u'Woat Dischkrian',
            'es': u'Anexo Discusión',
            'fi': u'Keskustelu kirjasta',
            'fr': u'Discussion Référence',
            'frr': u'Index Diskussion',
            'lt': u'Sąrašo aptarimas',
            'pt': u'Livro Discussão',
            'ru': u'Обсуждение проекта',
        }

        self.namespaces[106] = {
            'als': u'Text',
            'bar': u'Text',
            'frr': u'Text',
            'ru': u'Арбитраж',
        }

        self.namespaces[107] = {
            'als': u'Text Diskussion',
            'bar': u'Text Dischkrian',
            'frr': u'Text Diskussion',
            'ru': u'Обсуждение арбитража',
        }

        self.namespaces[108] = {
            'als': u'Spruch',
            'bar': u'Spruch',
            'en': u'Book',
            'he': u'ספר',
            'ro': u'Cod',
            'yo': u'Ìwé',
        }

        self.namespaces[109] = {
            'als': u'Spruch Diskussion',
            'bar': u'Spruch Dischkrian',
            'en': u'Book talk',
            'he': u'שיחת ספר',
            'ro': u'Discuție Cod',
            'yo': u'Ọ̀rọ̀ ìwé',
        }

        self.namespaces[110] = {
            'als': u'Nochricht',
            'bar': u'Nochricht',
        }

        self.namespaces[111] = {
            'als': u'Nochricht Diskussion',
            'bar': u'Nochricht Dischkrian',
        }

        self.namespaces[446] = {
            'en': u'Education Program',
            'he': u'הוראה',
            'mk': u'Education Program',
            'sv': u'Education Program',
        }

        self.namespaces[447] = {
            'en': u'Education Program talk',
            'he': u'שיחת הוראה',
            'mk': u'Education Program talk',
            'sv': u'Education Program talk',
        }

        self.namespaces[710] = {
            'en': u'TimedText',
        }

        self.namespaces[711] = {
            'en': u'TimedText talk',
        }

        self.category_redirect_templates = {
            '_default': (),
            'ar': (u'تحويل تصنيف',
                   u'تحويلة تصنيف',
                   u'Category redirect',),
            'arz': (u'تحويل تصنيف',),
            'cs': (u'Zastaralá kategorie',),
            'da': (u'Kategoriomdirigering',),
            'en': (u'Category redirect',
                   u'Category Redirect',
                   u"Categoryredirect",
                   u'Catredirect',
                   u'Cat redirect',),
            'es': (u'Categoría redirigida',),
            'eu': (u'Kategoria redirect',),
            'fa': (u'رده بهتر',
                   u'انتقال رده',
                   u'فیلم‌های امریکایی',),
            'fr': (u'Redirection de catégorie',),
            'gv': (u'Aastiurey ronney',),
            'hi': (u'श्रेणीअनुप्रेषित',
                   u'Categoryredirect',),
            'hu': (u'Kat-redir',
                   u'Katredir',
                   u'Kat-redirekt',),
            'id': (u'Alih kategori',
                   u'Alihkategori',),
            'ja': (u'Category redirect',),
            'ko': (u'분류 넘겨주기',),
            'mk': (u'Премести категорија',),
            'ml': (u'Category redirect',),
            'ms': (u'Pengalihan kategori',
                   u'Categoryredirect',
                   u'Category redirect',),
            'mt': (u'Redirect kategorija',),
            'no': (u'Category redirect',
                   u'Kategoriomdirigering',
                   u'Kategori-omdirigering',),
            'pl': (u'Przekierowanie kategorii',
                   u'Category redirect',),
            'pt': (u'Redirecionamento de categoria',
                   u'Redircat',
                   u'Redirect-categoria',),
            'ro': (u'Redirect categorie',),
            'ru': (u'Переименованная категория',
                   u'Categoryredirect',
                   u'CategoryRedirect',
                   u'Category redirect',
                   u'Catredirect',),
            'simple': (u'Category redirect',
                       u'Categoryredirect',
                       u'Catredirect',),
            'sl': (u'Category redirect',),
            'sq': (u'Kategori e zhvendosur',
                   u'Category redirect',),
            'sv': (u'Kategoriomdirigering',
                   u'Omdirigering kategori',),
            'tl': (u'Category redirect',),
            'tr': (u'Kategori yönlendirme',
                   u'Kat redir',),
            'uk': (u'Categoryredirect',),
            'vi': (u'Đổi hướng thể loại',
                   u'Thể loại đổi hướng',
                   u'Chuyển hướng thể loại',
                   u'Categoryredirect',
                   u'Category redirect',
                   u'Catredirect',),
            'yi': (u'קאטעגאריע אריבערפירן',),
            'zh': (u'分类重定向',
                   u'Cr',
                   u'CR',
                   u'Cat-redirect',),
            'zh-yue': (u'Category redirect',
                       u'分類彈去',
                       u'分類跳轉',),
        }

        self.disambiguationTemplates = {
            # If no templates are given, retrieve names from  the live wiki
            # ([[MediaWiki:Disambiguationspage]])
            # first char must be in uppercase
            '_default': [u'Disambig'],  # for default MediaWiki message only
            'haw': [u'Huaʻōlelo puana like'],
            'no':  [u'Peker', u'Etternavn', u'Disambig',
                    u'Tobokstavsforkortelse', u'Trebokstavsforkortelse',
                    u'Flertydig', u'Pekerside'],
            'nov': [u'Desambig'],
            'qu':  [u"Sut'ichana qillqa", u'Disambig', u'SJM'],
            'rmy': [u'Dudalipen'],
            'sk':  [u'Disambig', u'Rozlišovacia stránka', u'Disambiguation'],
            'tg':  [u'Ибҳомзудоӣ', u'Disambig', u'Рафъи ибҳом',
                    u'Disambiguation'],
            'tr':  [u'Anlam ayrım', u'Disambig', u'Anlam ayrımı',
                    u'Kişi adları (anlam ayrımı)',
                    u'Yerleşim yerleri (anlam ayrımı)',
                    u'kısaltmalar (anlam ayrımı)', u'Coğrafya (anlam ayrımı)',
                    u'Yerleşim yerleri (anlam ayrımı)', u'Sayılar (anlam ayrımı)',
                    u"ABD'deki iller (anlam ayrımı)"],
            'wo':  [u'Bokktekki'],
            'yi':  [u'באדייטען'],
            'zea': [u'Dp', u'Deurverwiespagina'],
            'zh-classical':  [u'釋義', u'消歧義', u'Disambig'],
        }

        self.disambcatname = {
            'af':  u'dubbelsinnig',
            'als': u'Begriffsklärung',
            'ang': u'Scīrung',
            'ast': u'Dixebra',
            'ar':  u'صفحات توضيح',
            'be':  u'Disambig',
            'be-x-old':  u'Вікіпэдыя:Неадназначнасьці',
            'bg':  u'Пояснителни страници',
            'ca':  u'Viquipèdia:Registre de pàgines de desambiguació',
            'cbk-zam': u'Desambiguo',
            'cs':  u'Rozcestníky',
            'cy':  u'Gwahaniaethu',
            'da':  u'Flertydig',
            'de':  u'Begriffsklärung',
            'el':  u'Αποσαφήνιση',
            'en':  u'All disambiguation pages',
            'eo':  u'Apartigiloj',
            'es':  u'Desambiguación',
            'et':  u'Täpsustusleheküljed',
            'eu':  u'Argipen orriak',
            'fa':  u'صفحه‌های ابهام‌زدایی',
            'fi':  u'Täsmennyssivut',
            'fo':  u'Fleiri týdningar',
            'fr':  u'Homonymie',
            'fy':  u'Trochferwiisside',
            'ga':  u'Idirdhealáin',
            'gl':  u'Homónimos',
            'he':  u'פירושונים',
            'hu':  u'Egyértelműsítő lapok',
            'ia':  u'Disambiguation',
            'id':  u'Disambiguasi',
            'io':  u'Homonimi',
            'is':  u'Aðgreiningarsíður',
            'it':  u'Disambigua',
            'ja':  u'曖昧さ回避',
            'ka':  u'მრავალმნიშვნელოვანი',
            'kw':  u'Folennow klerheans',
            'ko':  u'동음이의어 문서',
            'ku':  u'Rûpelên cudakirinê',
            'krc': u'Кёб магъаналы терминле',
            'ksh': u'Woot met mieh wi ëijnem Senn',
            'la':  u'Discretiva',
            'lb':  u'Homonymie',
            'li':  u'Verdudelikingspazjena',
            'ln':  u'Bokokani',
            'lt':  u'Nuorodiniai straipsniai',
            'ms':  u'Nyahkekaburan',
            'mt':  u'Diżambigwazzjoni',
            'nds': u'Mehrdüdig Begreep',
            'nds-nl': u'Wikipedie:Deurverwiespagina',
            'nl':  u'Wikipedia:Doorverwijspagina',
            'nn':  u'Fleirtydingssider',
            'no':  u'Pekere',
            'pl':  u'Strony ujednoznaczniające',
            'pt':  u'Desambiguação',
            'ro':  u'Dezambiguizare',
            'ru':  u'Многозначные термины',
            'scn': u'Disambigua',
            'sk':  u'Rozlišovacie stránky',
            'sl':  u'Razločitev',
            'sq':  u'Kthjellime',
            'sr':  u'Вишезначна одредница',
            'su':  u'Disambiguasi',
            'sv':  u'Förgreningssider',
            'szl': u'Zajty ujydnoznačńajůnce',
            'th':  u'การแก้ความกำกวม',
            'tl':  u'Paglilinaw',
            'tr':  u'Anlam ayrım',
            'uk':  u'Багатозначні геопункти',
            'vi':  u'Trang định hướng',
            'vo':  u'Telplänovapads',
            'wa':  u'Omonimeye',
            'zea': u'Wikipedia:Deurverwiespagina',
            'zh':  u'消歧义',
            'zh-min-nan': u'Khu-pia̍t-ia̍h',
        }

        # families that redirect their interlanguage links here.
        self.interwiki_forwarded_from = [
            'commons',
            'incubator',
            'meta',
            'species',
            'strategy',
            'test',
        ]

        # Global bot allowed languages on
        # http://meta.wikimedia.org/wiki/Bot_policy/Implementation#Current_implementation
        self.cross_allowed = [
            'ab', 'ace', 'af', 'ak', 'als', 'am', 'an', 'ang', 'ar', 'arc',
            'arz', 'as', 'ast', 'av', 'ay', 'az', 'ba', 'bar', 'bat-smg', 'bcl',
            'be', 'be-x-old', 'bg', 'bh', 'bi', 'bjn', 'bm', 'bo', 'bpy', 'bug',
            'bxr', 'ca', 'cbk-zam', 'cdo', 'ce', 'ceb', 'ch', 'chr', 'chy',
            'ckb', 'co', 'cr', 'crh', 'csb', 'cu', 'cv', 'cy', 'da', 'diq',
            'dsb', 'dz', 'ee', 'el', 'eml', 'en', 'eo', 'et', 'eu', 'ext', 'fa',
            'ff', 'fi', 'fj', 'fo', 'frp', 'frr', 'fur', 'ga', 'gag', 'gan',
            'gd', 'glk', 'gn', 'got', 'gu', 'gv', 'ha', 'hak', 'haw', 'he',
            'hi', 'hif', 'hr', 'hsb', 'ht', 'hu', 'hy', 'ia', 'ie', 'ig', 'ik',
            'ilo', 'io', 'iu', 'ja', 'jbo', 'jv', 'ka', 'kaa', 'kab', 'kdb',
            'kg', 'ki', 'kk', 'kl', 'km', 'kn', 'ko', 'koi', 'krc', 'ks', 'ku',
            'kv', 'kw', 'ky', 'la', 'lad', 'lb', 'lbe', 'lez', 'lg', 'li',
            'lij', 'lmo', 'ln', 'lo', 'lt', 'ltg', 'lv', 'map-bms', 'mdf', 'mg',
            'mhr', 'mi', 'mk', 'ml', 'mn', 'mrj', 'ms', 'mwl', 'my', 'myv',
            'mzn', 'na', 'nah', 'nap', 'nds-nl', 'ne', 'new', 'nl', 'no', 'nov',
            'nrm', 'nso', 'nv', 'ny', 'oc', 'om', 'or', 'os', 'pa', 'pag',
            'pam', 'pap', 'pdc', 'pfl', 'pi', 'pih', 'pms', 'pnb', 'pnt', 'ps',
            'qu', 'rm', 'rmy', 'rn', 'roa-rup', 'roa-tara', 'ru', 'rue', 'rw',
            'sa', 'sah', 'sc', 'scn', 'sco', 'sd', 'se', 'sg', 'sh', 'si',
            'simple', 'sk', 'sm', 'sn', 'so', 'srn', 'ss', 'st', 'stq', 'su',
            'sv', 'sw', 'szl', 'ta', 'te', 'tet', 'tg', 'th', 'ti', 'tk', 'tl',
            'tn', 'to', 'tpi', 'tr', 'ts', 'tt', 'tum', 'tw', 'ty', 'udm', 'ug',
            'uz', 've', 'vec', 'vep', 'vls', 'vo', 'wa', 'war', 'wo', 'wuu',
            'xal', 'xh', 'yi', 'yo', 'za', 'zea', 'zh', 'zh-classical',
            'zh-min-nan', 'zh-yue', 'zu',
        ]

        # On most Wikipedias page names must start with a capital letter,
        # but some languages don't use this.
        self.nocapitalize = ['jbo']

        # Which languages have a special order for putting interlanguage links,
        # and what order is it? If a language is not in interwiki_putfirst,
        # alphabetical order on language code is used. For languages that are in
        # interwiki_putfirst, interwiki_putfirst is checked first, and
        # languages are put in the order given there. All other languages are
        # put after those, in code-alphabetical order.

        self.alphabetic_sr = [
            'ace', 'kbd', 'af', 'ak', 'als', 'am', 'ang', 'ab', 'ar', 'an',
            'arc', 'roa-rup', 'frp', 'arz', 'as', 'ast', 'gn', 'av', 'ay', 'az',
            'bjn', 'id', 'ms', 'bg', 'bm', 'zh-min-nan', 'nan', 'map-bms', 'jv',
            'su', 'ba', 'be', 'be-x-old', 'bh', 'bcl', 'bi', 'bn', 'bo', 'bar',
            'bs', 'bpy', 'br', 'bug', 'bxr', 'ca', 'ceb', 'ch', 'cbk-zam', 'sn',
            'tum', 'ny', 'cho', 'chr', 'co', 'cy', 'cv', 'cs', 'da', 'dk',
            'pdc', 'de', 'nv', 'dsb', 'na', 'dv', 'dz', 'mh', 'et', 'el', 'eml',
            'en', 'myv', 'es', 'eo', 'ext', 'eu', 'ee', 'fa', 'hif', 'fo', 'fr',
            'fy', 'ff', 'fur', 'ga', 'gv', 'sm', 'gag', 'gd', 'gl', 'gan', 'ki',
            'glk', 'got', 'gu', 'ha', 'hak', 'xal', 'haw', 'he', 'hi', 'ho',
            'hsb', 'hr', 'hy', 'io', 'ig', 'ii', 'ilo', 'ia', 'ie', 'iu', 'ik',
            'os', 'xh', 'zu', 'is', 'it', 'ja', 'ka', 'kl', 'kr', 'pam', 'krc',
            'csb', 'kk', 'kw', 'rw', 'ky', 'mrj', 'rn', 'sw', 'km', 'kn', 'ko',
            'kv', 'kg', 'ht', 'ks', 'ku', 'kj', 'lad', 'lbe', 'la', 'ltg', 'lv',
            'to', 'lb', 'lez', 'lt', 'lij', 'li', 'ln', 'lo', 'jbo', 'lg',
            'lmo', 'hu', 'mk', 'mg', 'mt', 'mi', 'min', 'cdo', 'mwl', 'ml',
            'mdf', 'mo', 'mn', 'mr', 'mus', 'my', 'mzn', 'nah', 'fj', 'ne',
            'nl', 'nds-nl', 'cr', 'new', 'nap', 'ce', 'frr', 'pih', 'no', 'nb',
            'nn', 'nrm', 'nov', 'oc', 'mhr', 'or', 'om', 'ng', 'hz', 'uz', 'pa',
            'pfl', 'pag', 'pap', 'koi', 'pi', 'pcd', 'pms', 'nds', 'pnb', 'pl',
            'pt', 'pnt', 'ps', 'aa', 'kaa', 'crh', 'ty', 'ksh', 'ro', 'rmy',
            'rm', 'qu', 'ru', 'rue', 'sa', 'sah', 'se', 'sg', 'sc', 'sco', 'sd',
            'stq', 'st', 'nso', 'tn', 'sq', 'si', 'scn', 'simple', 'ss', 'sk',
            'sl', 'cu', 'szl', 'so', 'ckb', 'srn', 'sr', 'sh', 'fi', 'sv', 'ta',
            'shi', 'tl', 'kab', 'roa-tara', 'tt', 'te', 'tet', 'th', 'ti', 'vi',
            'tg', 'tokipona', 'tp', 'tpi', 'chy', 've', 'tr', 'tk', 'tw', 'udm',
            'uk', 'ur', 'ug', 'za', 'vec', 'vep', 'vo', 'fiu-vro', 'wa', 'vls',
            'war', 'wo', 'wuu', 'ts', 'xmf', 'yi', 'yo', 'diq', 'zea', 'zh',
            'zh-tw', 'zh-cn', 'zh-classical', 'zh-yue', 'bat-smg',
        ]

        self.interwiki_putfirst = {
            'be-x-old': self.alphabetic,
            'en': self.alphabetic,
            'et': self.alphabetic_revised,
            'fi': self.alphabetic_revised,
            'fiu-vro': self.alphabetic_revised,
            'fy': self.fyinterwiki,
            'he': ['en'],
            'hu': ['en'],
            'lb': self.alphabetic,
            'mk': self.alphabetic,
            'ms': self.alphabetic_revised,
            'nds': ['nds-nl'],
            'nds-nl': ['nds'],
            'nn': ['no', 'sv', 'da'] + self.alphabetic,
            'no': self.alphabetic,
            'nv': ['en', 'es'] + self.alphabetic,
            'pdc': ['de', 'en'],
            'pl': self.alphabetic,
            'simple': self.alphabetic,
            'sr': self.alphabetic_sr,
            'sv': self.alphabetic,
            'te': ['en', 'hi', 'kn', 'ta', 'ml'],
            'ur': ['ar', 'fa', 'en'] + self.alphabetic,
            'vi': self.alphabetic_revised,
            'yi': ['en', 'he', 'de']
        }

        self.obsolete = {
            'aa': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Afar_Wikipedia
            'cho': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Choctaw_Wikipedia
            'dk': 'da',
            'ho': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Hiri_Motu_Wikipedia
            'hz': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Herero_Wikipedia
            'ii': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Yi_Wikipedia
            'kj': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Kwanyama_Wikipedia
            'kr': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Kanuri_Wikipedia
            'mh': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Marshallese_Wikipedia
            'minnan': 'zh-min-nan',
            'mo': 'ro',  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Moldovan_Wikipedia
            'mus': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Muscogee_Wikipedia
            'nan': 'zh-min-nan',
            'nl_nds': 'nl-nds',  # miss-spelling
            'nb': 'no',
            'ng': None,  # (not reachable) http://meta.wikimedia.org/wiki/Inactive_wikis
            'jp': 'ja',
            'ru-sib': None,  # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Siberian_Wikipedia
            'tlh': None,
            'tokipona': None,
            'zh-tw': 'zh',
            'zh-cn': 'zh'
        }

        # Languages that used to be coded in iso-8859-1
        self.latin1old = [
            'de', 'en', 'et', 'es', 'ia', 'la', 'af', 'cs', 'fr', 'pt', 'sl',
            'bs', 'fy', 'vi', 'lt', 'fi', 'it', 'no', 'simple', 'gl', 'eu',
            'nds', 'co', 'mi', 'mr', 'id', 'lv', 'sw', 'tt', 'uk', 'vo', 'ga',
            'na', 'es', 'nl', 'da', 'dk', 'sv', 'test']

        self.crossnamespace[0] = {
            '_default': {
                'pt': [102],
                'als': [104],
                'ar': [104],
                'de': [4],
                'en': [12],
                'es': [104],
                'fi': [4],
                'fr': [104],
                'hr': [102],
                'lt': [104],
            },
            'km': {
                '_default': [0, 4, 12],
            },
            #wrong wikipedia namespace alias
            'mzn': {
                '_default': [0, 4],

            },
        }
        self.crossnamespace[1] = {
            '_default': {
                'pt': [103],
                'als': [105],
                'ar': [105],
                'en': [13],
                'es': [105],
                'fi': [5],
                'fr': [105],
                'hr': [103],
                'lt': [105],
            },
        }
        self.crossnamespace[4] = {
            '_default': {
                '_default': [12],
            },
            'de': {
                '_default': [0, 10, 12],
                'el': [100, 12],
                'es': [104, 12],
            },
            'fi': {
                '_default': [0, 12]
            },
            'mzn': {
                '_default': [0, 12]
            },
        }
        self.crossnamespace[5] = {
            'fi': {
                '_default': [1]}
        }
        self.crossnamespace[12] = {
            '_default': {
                '_default': [4],
            },
            'en': {
                '_default': [0, 4],
            },
        }
        self.crossnamespace[13] = {
            'en': {
                '_default': [0],
            },
        }
        self.crossnamespace[102] = {
            'pt': {
                '_default': [0],
                'als': [0, 104],
                'ar': [0, 104],
                'es': [0, 104],
                'fr': [0, 104],
                'lt': [0, 104]
            },
            'hr': {
                '_default': [0],
                'als': [0, 104],
                'ar': [0, 104],
                'es': [0, 104],
                'fr': [0, 104],
                'lt': [0, 104]
            },
        }
        self.crossnamespace[103] = {
            'pt': {
                '_default': [1],
                'als': [1, 105],
                'es': [1, 105],
                'fr': [1, 105],
                'lt': [1, 105]
            },
            'hr': {
                '_default': [1],
                'als': [1, 105],
                'es': [1, 105],
                'fr': [1, 105],
                'lt': [1, 105]
            },
        }
        self.crossnamespace[104] = {
            'als': {
                '_default': [0],
                'pt': [0, 102],
                'hr': [0, 102],
            },
            'ar': {
                '_default': [0, 100],
                'hr': [0, 102],
                'pt': [0, 102],
            },
            'es': {
                '_default': [0],
                'pt': [0, 102],
                'hr': [0, 102],
            },
            'fr': {
                '_default': [0],
                'pt': [0, 102],
                'hr': [0, 102],
            },
            'lt': {
                '_default': [0],
                'pt': [0, 102],
                'hr': [0, 102],
            },
        }
        self.crossnamespace[105] = {
            'als': {
                '_default': [1],
                'pt': [0, 103],
                'hr': [0, 103],
            },
            'ar': {
                '_default': [1, 101],
            },
            'es': {
                '_default': [1],
                'pt': [0, 103],
                'hr': [0, 103],
            },
            'fr': {
                '_default': [1],
                'pt': [0, 103],
                'hr': [0, 103],
            },
            'lt': {
                '_default': [1],
                'pt': [0, 103],
                'hr': [0, 103],
            },
        }

    def get_known_families(self, site):
        # In Swedish Wikipedia 's:' is part of page title not a family
        # prefix for 'wikisource'.
        if site.language() == 'sv':
            d = self.known_families.copy()
            d.pop('s')
            d['src'] = 'wikisource'
            return d
        else:
            return self.known_families

    def dbName(self, code):
        # returns the name of the MySQL database
        # for historic reasons, the databases are called xxwiki instead of
        # xxwikipedia for Wikipedias.
        return '%swiki_p' % code

    def code2encodings(self, code):
        """Return a list of historical encodings for a specific language
           wikipedia"""
        # Historic compatibility
        if code == 'pl':
            return 'utf-8', 'iso8859-2'
        if code == 'ru':
            return 'utf-8', 'iso8859-5'
        if code in self.latin1old:
            return 'utf-8', 'iso-8859-1'
        return self.code2encoding(code),

    def shared_data_repository(self, code, transcluded=False):
        return ('wikidata', 'wikidata')
